name: Setup Lightsail Runner

# Allows the action to be triggered manually via the GitHub UI
on:
  workflow_dispatch:

jobs:
  setup-lightsail-runner:
    name: Setup Lightsail-Runner Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v1

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-cli@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  # Ensure this matches your region

      - name: Run Lightsail-Runner Setup
        run: |
          chmod +x ./scripts/setup_lightsail_runner.sh
          ./scripts/setup_lightsail_runner.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_REGION: eu-central-1
          AVAILABILITY_ZONE: eu-central-1a
          BLUEPRINT_ID: ubuntu_20_04
          BUNDLE_ID: nano_2_0
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
